microsoft/archai

- archai/cifar10_models/alexnet.py
Added AlexNet architecture under archai/archai/cifar10_models.
There are some architecture changes in this model as compared to the pytorch/vision/torchvision/models/alexnet.py 
Here, I kept the number of filters of the Convolutional blocks as [96,256,384,384,256], as is given in the [original paper](https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks).
Besides, I also added the code for weight and bias initialization (following [the paper](https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks)).
> Added AlexNet architecture

- archai/data_aug/search.py
[flake8](http://flake8.pycqa.org) testing of https://github.com/microsoft/archai on Python 3.9.0rc2+
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./archai/data_aug/search.py:343:13: E999 SyntaxError: invalid syntax
, aug, cutout,
^
1     E999 SyntaxError: invalid syntax
1
```
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead, these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has …
> Fix Python syntax error in search.py

- archai/algos/petridish/evaluater_petridish.py
split('.') may cause problems as folders can have '.' in their name.
> Fix Petridish checkpoint path

- archai/nlp/nvidia_transformer_xl/mem_transformer.py
- archai/nlp/nvidia_transformer_xl/nvidia_utils/exp_utils.py
- archai/nlp/nvidia_transformer_xl/qat.py
- archai/nlp/nvidia_transformer_xl/train.py
Implements Conv1d QAT and QAT finetuning where a pretrained model is loaded.
1. Changes the way cache_dir argument is interpreted. If an absolute path is passed, it will be used as is. If a relative path is passed, it will be joined with 'datadir'. This makes it easy to have multiple caches with different configs. The default behavior remans the same.
2. Adds argument 'pretrained_path' so that we can load a model for finetuning. If an absolute path it will be used as is, if relative it will be joined with the parent folder of 'output_dir'. This allows for local and cluster use.
> Conv1d qat training

- archai/nlp/nvidia_transformer_xl/eval.py
- archai/nlp/nvidia_transformer_xl/mem_transformer.py
- archai/nlp/nvidia_transformer_xl/nvidia_utils/lm_iterators.py
- archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/export.py
- archai/nlp/nvidia_transformer_xl/train.py
- archai/nlp/scoring/model_wrapper.py
This PR addresses the following issues:
* Changes the shape of input tensors to `[batch_size, seq_len]` instead of the opposite. Such improvement will allow for a more cleaner interface and allow users in using a shape standard that has been proposed by the NLP/Transformer-based community;
* Fixes the creation of `attention_masks` by including the length of `past_key_values` whenever they are used;
* Fixes `wt2` to `wt103` in configuration file. We should be using the same dataset identifier since the file explicitly says that is WikiText-103 for Transformer-XL Base;
* Removes unused key `num_attention_heads` from ONNX export.
*Note that to change the shape of input tensors, several files needed to be modified, including the ones from `scoring` and `nvidia_utils`* packages.
> pr(archai): Changes the shape ordering to: batch_size x seq_len.

- archai/nlp/nvidia_transformer_xl/eval.py
- archai/nlp/nvidia_transformer_xl/mem_transformer.py
- archai/nlp/nvidia_transformer_xl/nvidia_utils/lm_iterators.py
- archai/nlp/nvidia_transformer_xl/nvidia_utils/proj_adaptive_softmax.py
- archai/nlp/nvidia_transformer_xl/train.py
- archai/nlp/scoring/model_wrapper.py
Although this PR seems to introduce a bit of changes, they are purely aesthetic to make Archai more compliant with Huggingface's Transformers. Every changed keyword inside `archai/nlp/` has been found and replaced whenever it was needed, while making sure to avoid inner architectural changes, i.e., the changes are mainly in the `MemTransformerLM` class and not in the child-layers classes.
The following changes have been made:
- `data` has been renamed to `input_ids` [1]
- `target` has been renamed to `labels` [1]
- `log_probs` has been renamed to `prediction_scores` [1]
- `return_nll` has been renamed to `output_loss` [1]
- `return_log_probs` has been renamed to `output_prediction_scores` [1]
- MemTransformerLM outputs have been changed from `(loss, mems, prediction_scores, …
> pr(archai): Introduces new nomenclature for input and output arguments, more like Huggingface's Transformers.

- archai/nlp/nvidia_transformer_xl/models/archai_model.py
- archai/nlp/nvidia_transformer_xl/models/available_models.py
- archai/nlp/nvidia_transformer_xl/models/hf_gpt2.py
- archai/nlp/nvidia_transformer_xl/models/hf_transfo_xl.py
- archai/nlp/nvidia_transformer_xl/models/model_list.py
- archai/nlp/nvidia_transformer_xl/models/model_utils.py
- archai/nlp/nvidia_transformer_xl/onnx/export_torch_to_onnx.py
- archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/configs.py
- archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/export.py
- archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/forward.py
- archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/load.py
- archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/opt/fusion_options.py
- archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/opt/opt_models.py
- archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/optimization.py
- archai/nlp/nvidia_transformer_xl/onnx/validate_onnx_export.py
- archai/nlp/nvidia_transformer_xl/train.py
This PR introduces the following changes:
- Adds license headers to new files;
- Fixes a bug when loading an `ArchaiModel` and not having PyTorch compiled with CUDA;
- Changes `models/model_list.py` to `models/available_models.py`;
- Allows for configurable ONNX exports;
- Allows for configurable ONNX optimizations.
_The order of PR merges should be the following: `gderosa/onnx_export` into `gderosa/transfo_xl` before `gderosa/transfo_xl` into `nlp`._
> pr(archai): Adds support for configurable ONNX exports.

- archai/nlp/compression/onnx/onnx_utils/export.py
- archai/nlp/compression/onnx/onnx_utils/onnx_loader.py
- archai/nlp/compression/quantization/modules.py
1. Fixes naming issues
2. Converts H.F. "Conv1D" to linear to avoid export break with relu squared.
> Fixed naming and converts Conv1D to linear

- archai/nlp/models/hf_gpt2/model_hf_gpt2.py
- archai/nlp/models/model_mixed_qat.py
- archai/nlp/train.py
- setup.py
1. Partial fix on GPT2Flex # of params (there's still a small diff compared to previous code)
2. Changes default qat scheduler (we won't be using cyclic_cosine anymore)
> Partial fix on # params GPT2Flex and default param

- archai/nlp/train.py
This PR introduces the following changes:
- Adds support for AMP using `bfloat16` when using PyTorch 1.10+ and Ampere-based GPUs.
> pr(archai): Adds support for bfloat16 when using PyTorch 1.10+ and Ampere GPU.

- devops/azure/runner.py
- devops/azure/upload.py
- devops/requirements.txt
requirements.txt
- Changed scikit-image version to match Python 3.6
upload.py
- Resource not found when uploading a model. Fixed by using update_status_entity();
- Node column in Azure Table was populated with the local machine's name, locking the workflow. Fixed by using update_status_entity()
runner.py
- All rows are getting skipped due to: _skip <model-name> for now until other quantization finishes on our node_. Although the model is already quantized, the column is not set as true. Fixed by correcting the logic of quantization verification.
- When there's a conversion error (e.g. onnx to dlc), the next state of the Azure Table does not reflect that. It gets stuck on "quantizing" or other unrelated status. Fixed by adding error checks.
> Fixing archai/devops workflow

- docs/conf.py
Updates a single `conf.py` with the correct order of `autodoc_mock_imports` and activates the documentation workflow.
> fix(docs): Fixes order of autodoc_mock_imports in conf.py.

- archai/discrete_search/evaluators/nlp/transformer_flex_latency.py
- archai/discrete_search/evaluators/nlp/transformer_flex_memory.py
- archai/onnx/export.py
- archai/onnx/onnx_loader.py
- tasks/text_generation/search.py
- Adds a `validate` option to choose whether validation should be performed during ONNX exports;
- Adds support on ONNX-based evaluators to use `validate` and `optimize` (whether optimization should be performed);
- Adds support for custom providers when loading an ONNX model (allows for GPU-based measurement using the `CUDAExecutionProvider`).
* Environment: Python 3.7/3.8
> pr(archai): Improves ONNX-based evaluators.

- .github/workflows/lint-run-unit-tests.yaml
- .github/workflows/lint-run-unitary-tests.yaml
- .github/workflows/run-notebook-tests.yml
- docs/contributing/unit_tests.rst
- docs/getting_started/notebooks/cv/pl_trainer.ipynb
- docs/getting_started/notebooks/discrete_search/algos.ipynb
- docs/index.rst
In progress.
Fixes: #155, #167 
> pr(archai): Fixes notebook-related issues.

- archai/discrete_search/algos/bananas.py
- archai/discrete_search/algos/evolution_pareto.py
- archai/discrete_search/algos/local_search.py
- archai/discrete_search/algos/random_search.py
- archai/discrete_search/algos/regularized_evolution.py
- archai/discrete_search/api/archai_model.py
- archai/discrete_search/api/search_results.py
- archai/discrete_search/search_spaces/nlp/transformer_flex/search_space.py
- tasks/text_generation/search.py
- Adds a `disable_weights_init` boolean disable weights initialization in `TransformerFlexSearchSpace`.
- Adds a `clear()` method to `ArchaiModel` that allows clearing loaded architectures from memory.
- Adds a `optimize_memory_usage` boolean to `EvolutionPareto` to clear architectures and optimize memory usage.
> Fixes memory overflow when running searches with `EvolutionPareto`

- archai/discrete_search/search_spaces/config/arch_config.py
* Adds new optional parameter `default` for `ArchConfig.pick` method to select a value in case the chosen `param_name` does not exist.
* Syntax sugar for checking if a param is set inside an `ArchConfig` object (implements `ArchConfig.__in__(param_name)`)
> feat(config): add `default` parameter for `ArchConfig.pick` method

- archai/datasets/nlp/fast_hf_dataset_provider.py
Fix `FastHfDatasetProvider` race condition when saving dataset splits
Fixes: #192
> fix(FastHfDatasetProvider): race condition

- archai/common/store.py
- setup.py
- tests/common/test_store.py
ArchaiStore wraps an Azure 'status' Table and associated Blob Storage used to provide a backing
store and collated status for long running jobs.  This is actually a general purpose utility class
that could be used for anything.  The 'status' table support a locking concept that allows the
status table to be used as a way or coordinating jobs across multiple machines
* Environment:
* OS:
- [] Corresponding changes to the documentation
> add azure storage helper

- .github/workflows/lint-run-unit-tests.yaml
- archai/common/file_utils.py
- archai/datasets/nlp/fast_hf_dataset_provider.py
- archai/datasets/nlp/fast_hf_dataset_provider_utils.py
- archai/discrete_search/evaluators/onnx_model.py
- archai/discrete_search/evaluators/progressive_training.py
- setup.py
- tests/common/test_file_utils.py
- tests/datasets/cv/test_mnist_dataset_provider.py
- tests/datasets/nlp/test_fast_hf_dataset_provider.py
- tests/datasets/nlp/test_hf_dataset_provider.py
- tests/datasets/nlp/test_nvidia_dataset_provider.py
- tests/discrete_search/api/test_search_objectives.py
- tests/trainers/cv/test_pl_trainer.py
Minor fixes required to make unit tests work on Windows, the main fix is in the area of handling a weird bug in `tempfile.NamedTemporaryFile` where you cannot open the file again on Windows.  This is fixed with a new file_util class named `TemporaryFiles`.  It also handles some problems with using "rmtree" to cleanup a dataset folder when a memory mapped file is still open in that folder.  Windows does not allow this, so the tests now ensure those memory mapped files are closed before attempting to remove the directory. This PR also adds cross-platform test matrix to our `lint-run-unit-tests.yaml` github workflow so the unit tests are now also run on Windows and they pass.  
Fixes: # 206
* Environment:
* OS:
> Fix unit tests so they work on Windows.

- archai/common/store.py
Entity locking was confused when the node column was equal to empty string.  This should mean the node is not locked.
* Environment:
* OS:
> fix bug in entity locking.

- archai/common/store.py
add retry logic to store to work around an error that can happen on azure VM's that are still booting up their network connections: azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x14952e8a71c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution.
* Environment:
* OS:
> add retry logic to store to work around an error that can happen 

- archai/discrete_search/algos/evolution_pareto.py
- tests/discrete_search/algos/test_evolution_pareto.py
- tests/discrete_search/search_spaces/config/test_config_ss.py
…en seed.
Add unit tests to cover this.
Fix some randomness in evolutionary pareto search not coming from given seed
I found this running my new AML version of the face segmentation task.  Each search run was generating different archid's even though I was giving the search algorithm the same seed.
* Environment:
* OS:
> Fix some randomness in evolutionary pareto search not coming from given seed
