.amltignore, .gitignore, .ptignore, __init__.py, setup.py
This pull request removes an unused `__init__.py` on the root folder and makes a small change regarding the nomenclature of older `.ptignore` (currently as `.amltignore`).
Additionally, it bumps the version on `setup.py` to one after the latest release, i.e., `0.5.2`.
=> fix(root): Removes unused files and cleanup the root folder.

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/regular-issue.md
This is a simple pull request that adds a `.github` folder with some pre-built templates, such as bug reports, feature requests and regular issues.
=> feature(issue_template): Adds templates for GitHub issues.

archai/nlp/nvidia_transformer_xl/mem_transformer.py, archai/nlp/nvidia_transformer_xl/nvidia_utils/lm_iterators.py, archai/nlp/nvidia_transformer_xl/train.py
This PR adds support for Dynamic Quantization, which is turned on by passing a `--dynamic_quantization` flag. All support layers are being quantized, i.e., linear and embedding, and the quantized model is being saved into a new checkpoint.
=> Adds support for Dynamic Quantization.

archai/nlp/nvidia_transformer_xl/onnx/export_torch_to_onnx.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/export.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/forward.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/load.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/operators.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/opt/fusion_options.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/opt/model.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/optimization.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/quantization.py, archai/nlp/nvidia_transformer_xl/onnx/validate_onnx_export.py, setup.py
I will open this PR so we can discuss about how would be the best way to put everything that is packed in proper folders and files.
**Folders**:
- `nvidia_transformer_xl/onnx`: Holds scripts used to export/validate an ONNX model and a sublevel package with ONNX utilities;
- `nvidia_transformer_xl/onnx/onnx_utils`: Holds utilities used to export MemTransformerLM into an ONNX model;
- `nvidia_transformer_xl/onnx/onnx_utils/opt`: Holds optimization utilities used to fuse the MemTransformerLM ONNX graph.
**Files**:
- `nvidia_transformer_xl/onnx/export_torch_to_onnx.py`: Script that exports a MemTransformerLM checkpoint into an ONNX model;
- `nvidia_transformer_xl/onnx/validate_onnx_export.py`: Script that validates between a MemTransformerLM checkpoint and exported ONNX model;
- …
=> [WIP] Supports ONNX exports

archai/nlp/nvidia_transformer_xl/nvidia_utils/corpus.py, archai/nlp/nvidia_transformer_xl/nvidia_utils/exp_utils.py, archai/nlp/tokenizer_utils/bbpe_vocab.py, archai/nlp/tokenizer_utils/gpt2_vocab.py
1. Changes defaults GPT2 vocab special tokens.
2. Applies preprocessing also to the tokenizer training.
=> Tokenizer tweaks

archai/nlp/nvidia_transformer_xl/models/archai_model.py, archai/nlp/nvidia_transformer_xl/models/hf_gpt2.py, archai/nlp/nvidia_transformer_xl/models/mem_transformer.py, archai/nlp/nvidia_transformer_xl/models/model_list.py, archai/nlp/nvidia_transformer_xl/train.py
1. Create an abstract model, ArchaiModel, from which all model must derive to be compatible with the codebase (train.py)
2. Adapts huggingface GPT2 model to our codebase (hf_gpt2.py)
3. Move all models to the 'models' folder.
=> Add hugging face GPT2 model.

archai/nlp/nvidia_transformer_xl/onnx/export_torch_to_onnx.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/configs.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/export.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/forward.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/load.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/opt/fusion_options.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/opt/opt_models.py, archai/nlp/nvidia_transformer_xl/onnx/onnx_utils/optimization.py, archai/nlp/nvidia_transformer_xl/onnx/validate_onnx_export.py, archai/nlp/nvidia_transformer_xl/train.py
This PR introduces the following changes:
- Adds support for exporting `HfGPT2` with ONNX;
- Adds support for optimizing exported `HfGPT2` with ONNX;
- Adds some unused arguments that might be useful when running ONNX export script.
=> pr(archai): Adds support for GPT2 export and optimization with ONNX.

archai/nlp/compression/onnx/export_torch_to_onnx.py, archai/nlp/compression/onnx/onnx_utils/export.py, archai/nlp/compression/onnx/onnx_utils/onnx_loader.py, archai/nlp/compression/onnx/onnx_utils/optimization.py, archai/nlp/models/model_dict.py
Enables the option of exporting the hf_gpt2_flex model.
=> Fixes hf_gpt2_flex export

archai/nlp/reports/__init__.py, archai/nlp/reports/dllogger_parser.py, archai/nlp/reports/report_base.py
This PR introduces the following changes:
- Adds a new `reports` module to the `nlp` package;
- Implements an initial draft to parse JSON-based logs from dllogger files and convert them to markdown tables.
=> pr(archai): Adds report-based functionalities to the NLP package.

devices/docker/Dockerfile, devices/docker/setup.ps1
Describe if additional tests have been implemented and reproduced.
* Platform:
* Environment:
=> update quantizer docker image

devices/docker/Dockerfile, devices/requirements.txt, devices/snpe/cleanup_results.py, devices/snpe/create_data.py, devices/snpe/test_snpe.py
Switch to SNPE SDK version snpe-1.64.0.3605
Describe if additional tests have been implemented and reproduced.
* Platform:
* Environment:
=> SNPE: switch to new SDK version snpe-1.64.0.3605

devices/azure/report_device_usage.py
Fixes: # device utilization report was not granular enough.
Describe if additional tests have been implemented and reproduced.
* Platform:
* Environment:
=> break down utilization by day.

archai/nlp/models/hf_opt/config_hf_opt.py
=> Defines proper hyperparameters for OPT-related search

archai/nlp/attribute_utils.py, archai/nlp/file_utils.py, archai/nlp/logging_utils.py, archai/nlp/parser_utils.py
=> chore(nlp): Adds few utilities used across nlp package.

archai/nlp/models/model_utils/optimizers.py, archai/nlp/trainer.py, archai/nlp/training_args.py
Adds modules for trainer, training arguments and custom optimizers.
=> chore(nlp): Adds trainer, training_args and custom optimizers modules.

archai/nlp/benchmark.py, archai/nlp/callback.py
Adds trainer addons modules: benchmark and callbacks.
=> chore(nlp): Adds trainer addons modules

archai/nlp/data/__init__.py, archai/nlp/data/collators.py, archai/nlp/data/loaders.py, archai/nlp/data/processors.py, archai/nlp/tokenizer.py
Adds a package with data-related functions and a module for tokenization.
=> chore(nlp): Adds data package and tokenizer module.

archai/nlp/eval/__init__.py, archai/nlp/eval/metrics.py, archai/nlp/eval/onnx_evaluator.py, archai/nlp/eval/text_predict/__init__.py, archai/nlp/eval/text_predict/text_predict_model.py, archai/nlp/eval/text_predict/text_predict_tokenizer.py, archai/nlp/eval/torch_evaluator.py
Adds a package with evaluation-related functions.
=> chore(nlp): Adds an evaluation package.

archai/nlp/data/collators.py, archai/nlp/eval/metrics.py, archai/nlp/model.py
Adds a module for base model and fixes every importlib path.
=> chore(nlp): Adds model module and fixes importlib paths.

archai/nlp/models/bert/__init__.py, archai/nlp/models/bert/bert_model.py, archai/nlp/models/bert/bert_tokenizer.py, archai/nlp/models/model_utils/char_tokenizer.py
Adds BERT model and tokenizer.
=> chore(models): Adds BERT model and tokenizer.

archai/discrete_search/algos/evolution_pareto.py, archai/discrete_search/api/archai_model.py, archai/discrete_search/search_spaces/natsbench_tss/search_space.py
- Added option to initialize Evolution Pareto Search from seed models
- __repr__ and __str__ methods for ArchaiModel
- Bug when saving and loading architectures from Natsbench search space
* Platform:
* Environment:
=> Discrete search feature

archai/discrete_search/api/archai_model.py, archai/discrete_search/api/objective.py, archai/discrete_search/objectives/ray.py, archai/discrete_search/objectives/torch_model.py, docs/conf.py, docs/reference/api.rst, docs/reference/api/archai.discrete_search.algos.rst, docs/reference/api/archai.discrete_search.api.rst, docs/reference/api/archai.discrete_search.objectives.rst, docs/reference/api/archai.discrete_search.rst, docs/reference/api/archai.discrete_search.search_spaces.rst
Basic documentation for discrete search module.
* Archai version: 0.6.7
* Platform: Ubuntu
* Environment: Python 3.8.13
=> Discrete search docs

archai/nlp/train.py
=> Adds Spanish dataset

archai/nlp/datasets/nvidia/tokenizer_utils/bbpe_vocab.py, archai/nlp/quantization/mixed_qat.py
Adapts MixedQAT and nvidia tokenizer to be compatible with HF Trainer.
* Environment:
* OS:
=> Adapt to work with HF training

.amltignore, README.md, setup.py
- Removes extra dependencies we had due to the `text_predict` module;
- Fixes an URL typo on `README.md`;
- Fixes a comment typo on `.amltignore`.
=> pr(archai): Removes old dependencies (from text_predict).

archai/discrete_search/evaluators/pt_profiler.py, docs/getting_started/notebooks/discrete_search/algos.ipynb, tests/discrete_search/api/test_search_objectives.py, tests/discrete_search/evaluators/test_pt_profiler.py
Adds peak CPU memory evaluator
=> feat(ds/eval): TorchPeakCPUMemory

research/lm_eval_harness/lm_eval_harness/lm_eval_hf_model.py
- Fixes inputs and model not being placed on proper device in `lm_eval_harness`.
=> fix(lm_eval_harness): Fixes inputs not being placed on device.

archai/discrete_search/algos/sucessive_halving.py, archai/discrete_search/api/model_evaluator.py, docs/getting_started/notebooks/discrete_search/evaluators.ipynb
just fixes a typo in a class name.
* Environment:
* OS:
=> Fix simple typo in class name "SucessiveHalving" should be 

archai/discrete_search/evaluators/onnx_model.py
Fixes: # 187
* Environment:
* OS:
=> Fix AvgOnnxLatency so onnx device configurable.

archai/discrete_search/search_spaces/config/arch_config.py
=> Fixes Arch Config "in" overwrite

.vscode/launch.json, archai/common/config.py, archai/common/utils.py, archai/datasets/cv/face_synthetics.py
add download capability to FaceSyntheticsDataset
add download_and_extract_zip helper
cleanup launch.json
The FaceSyntheticsDataset can now download the full training dataset from web url, this is needed to implement AML training of the face segmentation task.
* Environment:
* OS:
=> add download capability to FaceSyntheticsDataset

archai/common/config.py, archai/common/monitor.py, archai/common/store.py, archai/discrete_search/evaluators/__init__.py, archai/discrete_search/evaluators/remote_azure_benchmark.py, setup.py
Add an Azure ML JobCompletionMonitor helper
Fix bug in ArchaiStore
Fix bugs in RemoteAzureBenchmarkEvaluator.
* Environment:
* OS:
=> Add environment variable expansion to Config class and some other helpers

archai/common/monitor.py
=> fix bug in check for complete status.

archai/common/store.py, tests/common/test_store.py
… very long time in long running jobs.
add retry logic to store to fix issues with tokens timing out after a very long time in long running jobs.
* Environment:
* OS:
=> add retry logic to store to fix issues with tokens timing out after a very long time in long running jobs.

archai/common/store.py, tests/common/test_store.py
Fix bug in merge_status_entity, add more unit test coverage
* Environment:
* OS:
=> Fix bug in merge_status_entity, add more unit test coverage

archai/datasets/nlp/fast_hf_dataset_provider.py
=> Ignore errors in loading tokenizer from_cache

tasks/facial_landmark_detection/dataset.py, tasks/facial_landmark_detection/latency.py, tasks/facial_landmark_detection/model.py, tasks/facial_landmark_detection/search.py, tasks/facial_landmark_detection/search_space.py, tasks/facial_landmark_detection/train.py, tasks/facial_landmark_detection/train_candidate_models.py, tasks/facial_landmark_detection/transforms.py
=> Autoformatted with black

setup.py
An error in the previous commit need to be fixed.
* Environment:
* OS:
=> Fix merging error

tasks/facial_landmark_detection/README.md
Amend a missing commit in the previous PR
* Environment:
* OS:
=> Missing a commit

tasks/face_segmentation/snp_test.py
These slight code adjustments aim to enhance Pythonic quality by incorporating the list comprehension 
NA
- Refactoring
* Environment:
* OS:
=> Refactoring
